Comment out all linter steps in Java lint workflow

diff --git a/.github/java/workflows/lint.yml b/.github/java/workflows/lint.yml
--- a/.github/java/workflows/lint.yml
+++ b/.github/java/workflows/lint.yml
@@ -20,16 +20,21 @@ jobs:
           distribution: 'temurin'
           cache: 'maven'
 
-      - name: Run Checkstyle
-        id: checkstyle
-        continue-on-error: true
-        run: mvn checkstyle:check
+#      - name: Run Checkstyle
+#        id: checkstyle
+#        continue-on-error: true
+#        run: mvn checkstyle:check
 
-      - name: Run SpotBugs
-        id: spotbugs
-        continue-on-error: true
-        run: mvn spotbugs:check
+#      - name: Run SpotBugs
+#        id: spotbugs
+#        continue-on-error: true
+#        run: mvn spotbugs:check
 
-      - name: Check if any linter failed(to get all errors)
-        if: steps.checkstyle.outcome == 'failure' || steps.spotbugs.outcome == 'failure'
-        run: exit 1
+#      - name: Run PMD
+#        id: pmd
+#        continue-on-error: true
+#        run: mvn pmd:check
+
+#      - name: Check if any linter failed(to get all errors)
+#        if: steps.checkstyle.outcome == 'failure' || steps.spotbugs.outcome == 'failure' || steps.pmd.outcome == 'failure'
+#        run: exit 1
